# Generated by Django 4.0.3 on 2022-03-22 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LastLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=16, max_digits=22)),
                ('image', models.ImageField(upload_to='geo-locations/')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Obstacles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=16, max_digits=22)),
            ],
        ),
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('inorganic_trash', models.DecimalField(decimal_places=2, max_digits=5)),
                ('organic_trash', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neer_bot.bot')),
            ],
        ),
    ]
